#! /bin/sh
#
# description: Starts and stops SSOLoginWebApp
#


# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 0
fi

# Avoid using root's TMPDIR
unset TMPDIR

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0


PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="SSOLoginWebApp Server"
NAME=SSOLoginWebApp
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

export ENV_CONFIG=PROD

do_start()
{
	echo "Starting SSOLoginWebApp  (background)..."
	cd $SOLR_HOME
	/bin/bash -l -c "/home/SSOLoginWebApp/start-service.sh" >/dev/null 2>&1 &
	return 0
}

do_stop()
{
	echo "Stopping SSOLoginWebApp"
	pkill -f SSOLoginWebApp
	rm -f $PIDFILE
	return 0
}

do_reload() {
	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
	return 0
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart)
	do_stop
	sleep 5
	case "$?" in
	  0|1)
		do_start
		;;
	  *)
		echo "Failed to restart"
		;;
	esac
	;;
  *)
	echo $"Usage: $SCRIPTNAME {start|stop|restart}"
	exit 1
	;;
esac

exit $?

